
module.exports = {
  url: 'https://developer-diary.netlify.com',
  title: '占位logo',
  tagline: 'Autodidact developer and sometimes hoop-jumper',
  copyright: '© 2019 Chris, All rights reserved',
  author: {
    name: 'Chris MiaoMiao',
    bio: 'Self-taught web developer and whisky aficionado',
    contacts: {
      linkedin: 'https://www.linkedin.com/in/will-ward-65234a170/',
      stackoverflow:
        'https://stackoverflow.com/users/10262432/will-ward?tab=profile',
      freecodecamp: 'https://www.freecodecamp.org/willjw3',
      twitter: 'https://twitter.com/willjw3',
    },
  },
  labels: [
    {
      tag: 'sports',
      tech: '体魄',
      name: 'GiThrowingBall',
      size: 20,
      color: 'red',
    },
    {
      tag: 'mindfulness',
      tech: '正念',
      name: 'GiAbstract024',
      size: 20,
      color: '#93b5cf',
    },
    {
      tag: 'communication',
      tech: '沟通',
      name: 'FaRocketchat',
      size: 20,
      color: '#aa6a4c',
    },
    {
      tag: 'read',
      tech: '阅读',
      name: 'FaBook',
      size: 20,
      color: '#bbb5ac',
    },
    {
      tag: 'write',
      tech: '写作',
      name: 'FaPencilAlt',
      size: 20,
      color: '#f28e16',
    },
    {
      tag: 'vuejs',
      tech: 'Vue',
      name: 'FaVuejs',
      size: 20,
      color: '#3eaf7c',
    },
    {
      tag: 'react',
      tech: 'React',
      name: 'DiReact',
      size: 20,
      color: 'deepskyblue',
    },
    {
      tag: 'nodejs',
      tech: 'Node.js',
      name: 'DiNodejsSmall',
      size: 20,
      color: 'lightgreen',
    },
    {
      tag: 'git',
      tech: 'Git',
      name: 'DiGitMerge',
      size: 20,
      color: 'white',
    },
    {
      tag: 'javascript',
      tech: 'JavaScript',
      name: 'DiJsBadge',
      size: 20,
      color: 'yellow',
    },
    {
      tag: 'css',
      tech: 'CSS',
      name: 'DiCss3Full',
      size: 20,
      color: 'teal',
    },
    {
      tag: 'python',
      tech: 'Python',
      name: 'DiPython',
      size: 20,
      color: 'deepskyblue',
    },
    {
      tag: 'html',
      tech: 'HTML',
      name: 'FaHtml5',
      size: 20,
      color: 'darkorange',
    },
    {
      tag: 'php',
      tech: 'php',
      name: 'DiPhp',
      size: 20,
      color: 'violet',
    },
    {
      tag: 'mongodb',
      tech: 'MongoDB',
      name: 'DiMongodb',
      size: 20,
      color: 'green',
    },
    {
      tag: 'mysql',
      tech: 'MySQL',
      name: 'DiMysql',
      size: 20,
      color: '#e97b00',
    },
    {
      tag: 'vscode',
      tech: 'VS Code',
      name: 'DiVisualstudio',
      size: 20,
      color: 'deepskyblue',
    },
  ],
}
